Bellatrix Jira Zephyr Plugin
AutomateThePlanet/BELLATRIX-Java pull request #37
Opened 2024-06-03 13:19 UTC by MiriamKyoseva

2024-06-05 13:07 UTC, n1xan commented on bellatrix.core/src/main/java/solutions/bellatrix/core/plugins/Plugin.java
> +
remove line

2024-06-05 13:07 UTC, n1xan commented on bellatrix.core/src/main/java/solutions/bellatrix/core/plugins/PluginExecutionEngine.java
> +
remove line

2024-06-05 13:07 UTC, n1xan commented on bellatrix.core/src/main/java/solutions/bellatrix/core/plugins/PluginExecutionEngine.java
> +
extra line here as well

2024-06-05 13:12 UTC, n1xan commented on bellatrix.plugins.jira.zephyr/src/main/java/plugins/jira/zephyr/ZephyrPlugin.java
> +        if (memberInfo.getDeclaringClass().isAnnotationPresent(ZephyrProject.class)) {
do we support the attribute only on the class level?

2024-06-05 13:13 UTC, n1xan commented on bellatrix.plugins.jira.zephyr/src/main/java/plugins/jira/zephyr/ZephyrPlugin.java
> +                return "";
add error log - Zephyr Project Id annotation not found on class level

2024-06-05 13:14 UTC, n1xan commented on bellatrix.plugins.jira.zephyr/src/main/java/plugins/jira/zephyr/ZephyrPlugin.java
> +                return "";
actually it is reading it from the config

2024-06-05 13:15 UTC, n1xan commented on bellatrix.plugins.jira.zephyr/src/main/java/plugins/jira/zephyr/ZephyrPlugin.java
> +                settings().getTestCycleName().isBlank() ? settings().getTestCycleName() : "BELLATRIX RUN");
this is fine for now, but potentially we would want to set this via Environment variable.

2024-06-05 13:15 UTC, n1xan commented on bellatrix.plugins.jira.zephyr/src/main/java/plugins/jira/zephyr/ZephyrPlugin.java
> +        var testCycle = new ZephyrTestCycle(settings().getDefaultProjectKey(), testCycleName, "In Progress");
maybe extract the statuses to enum?

2024-06-05 13:17 UTC, n1xan commented on bellatrix.plugins.jira.zephyr/src/main/java/plugins/jira/zephyr/ZephyrPlugin.java
> +    private ZephyrLocalData data;
this is a bit generic - I would rename it to zaphyrData

2024-06-05 13:18 UTC, n1xan commented on bellatrix.plugins.jira.zephyr/src/main/java/plugins/jira/zephyr/ZephyrPlugin.java
> +    @Getter @Setter
a class in the class? We usually create them in separate files

2024-06-05 13:20 UTC, n1xan requested changes
Please review and fix the PR comments.

2024-07-09 06:08 UTC, teo-nikolov approved these changes

2024-07-09 07:07 UTC, merged